project:
  type: website
  output-dir: "."

brand: _brand.yml

website: 
  title: "Chris Muris"
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    right: "Last updated: December 2025"
  navbar: 
    search: true

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    toc-location: left
    toc-float: true