project:
  type: website
  output-dir: "."

brand: _brand.yml

website: 
  navbar: 
    search: true

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    toc-location: left
    toc-float: true